server:
  port: 8086
spring:
  cloud:
    stream:
      function:
        definiton: movie2020
      bindings:
        movie2020-in-0:
          destination: movie2020  
      kafka:
        bindings:
          movie2020-in-0:
            consumer:
              configuration:
                value:
                   deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
        brokers:
          - localhost:9001
          - localhost:9002
                            