server:
  port: 8085
spring:
  cloud:
    stream:
      function:
        definiton: movieProcessing
      bindings:
        movieProcessing-in-0:
          destination: movie      
        movieProcessing-out-0:
          destination: movie2020
      kafka:
        bindings:
          movieProcessing-in-0:
            consumer:
              configuration:
                value:
                   deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          movieProcessing-out-0:
            producer:
              configuration:
                value:
                   serializer: org.springframework.kafka.support.serializer.JsonSerializer
      binder:
        brokers:
          - localhost:9001
          - localhost:9002
                            